In [1]:
import pandas as pd
from pickle import dump, load

In [2]:
from reports import CountryReports

# CountryReports

In [3]:
usa_instance = CountryReports('usa')

## Test DB Funcs

In [4]:
rooms_by_carecenter = usa_instance.rooms_by_carecenter()
rooms_by_carecenter

Accessing DC: usa

    care_center_id         room_id    rate room_type
0         cc-usa-1     r-usa-i-119  410.26   Class I
1         cc-usa-1     r-usa-i-140  410.26   Class I
2         cc-usa-1     r-usa-i-185  410.26   Class I
3         cc-usa-1     r-usa-i-276  410.26   Class I
4         cc-usa-1     r-usa-i-327  410.26   Class I
..             ...             ...     ...       ...
192       cc-usa-2  r-usa-vvip-750  827.07      VVIP
193       cc-usa-2  r-usa-vvip-797  827.07      VVIP
194       cc-usa-2  r-usa-vvip-809  827.07      VVIP
195       cc-usa-2  r-usa-vvip-865  827.07      VVIP
196       cc-usa-2  r-usa-vvip-931  827.07      VVIP

[197 rows x 4 columns]

In [6]:
with open('./usa_test/rooms_by_carecenter.pkl', 'wb') as fh:
    dump(rooms_by_carecenter, fh)

In [7]:
with open('./usa_test/rooms_by_carecenter.pkl', 'rb') as fh:
    loaded = load(fh)

loaded

    care_center_id         room_id    rate room_type
0         cc-usa-1     r-usa-i-119  410.26   Class I
1         cc-usa-1     r-usa-i-140  410.26   Class I
2         cc-usa-1     r-usa-i-185  410.26   Class I
3         cc-usa-1     r-usa-i-276  410.26   Class I
4         cc-usa-1     r-usa-i-327  410.26   Class I
..             ...             ...     ...       ...
192       cc-usa-2  r-usa-vvip-750  827.07      VVIP
193       cc-usa-2  r-usa-vvip-797  827.07      VVIP
194       cc-usa-2  r-usa-vvip-809  827.07      VVIP
195       cc-usa-2  r-usa-vvip-865  827.07      VVIP
196       cc-usa-2  r-usa-vvip-931  827.07      VVIP

[197 rows x 4 columns]

In [9]:
beds_by_room = usa_instance.beds_by_room()
beds_by_room

Accessing DC: usa

            room_id     bed_id care_center_id
0    r-usa-vvip-585  b-usa-696       cc-usa-2
1    r-usa-vvip-585    b-usa-9       cc-usa-2
2    r-usa-vvip-837  b-usa-135       cc-usa-2
3    r-usa-vvip-837   b-usa-39       cc-usa-1
4    r-usa-vvip-837  b-usa-399       cc-usa-2
..              ...        ...            ...
863   r-usa-vvip-48  b-usa-184       cc-usa-1
864   r-usa-vvip-48  b-usa-256       cc-usa-2
865   r-usa-vvip-48  b-usa-763       cc-usa-2
866   r-usa-vvip-48  b-usa-775       cc-usa-2
867   r-usa-vvip-48   b-usa-83       cc-usa-2

[868 rows x 3 columns]

In [10]:
with open('./usa_test/beds_by_room.pkl', 'wb') as fh:
    dump(beds_by_room, fh)

In [11]:
carecenters_by_city = usa_instance.carecenters_by_city()
carecenters_by_city

Accessing DC: usa

  city care_center_id                         address    care_center_name
0    B       cc-usa-1  (87241 Mitc, B, T, 73465, USA)  Global Health MVCH
1    D       cc-usa-2  (84386 Blac, D, I, 25814, USA)        MedStar MVCH

In [15]:
carecenters_by_state = usa_instance.carecenters_by_state()
carecenters_by_state

Accessing DC: usa

  state care_center_id                         address    care_center_name
0     T       cc-usa-1  (87241 Mitc, B, T, 73465, USA)  Global Health MVCH
1     I       cc-usa-2  (84386 Blac, D, I, 25814, USA)        MedStar MVCH

In [16]:
carecenters_by_country = usa_instance.carecenters_by_country()
carecenters_by_country

Accessing DC: usa

  country care_center_id                         address    care_center_name
0     USA       cc-usa-1  (65681 Chri, Y, O, 18960, USA)  Global Health MVCH
1     USA       cc-usa-2  (6367 Santa, A, U, 22391, USA)        MedStar MVCH

In [17]:
patient_admissions_by_carecenter = usa_instance.patient_admissions_by_carecenter()
patient_admissions_by_carecenter

Accessing DC: usa

,care_center_id,admission_id,admitted_causes,admitted_date,bed_id,discharged_date,patient_id,room_id,room_rate_per_night,room_rate_total
0,cc-usa-1,adm-usa-0011,Common spider bite spider bite,2015-01-04,b-usa-1568,2015-01-13,p-usa-0956,r-usa-vip-2595,520.66,4685.94
1,cc-usa-1,adm-usa-0016,Compartment syndrome increased pressure inside...,2016-04-09,b-usa-5082,2016-05-03,p-usa-0564,r-usa-iii-2962,77.11,1850.64
2,cc-usa-1,adm-usa-0024,Hepatitis A,2013-08-29,b-usa-5041,2013-09-04,p-usa-0649,r-usa-iii-7582,77.11,462.66
3,cc-usa-1,adm-usa-0057,Anemia (low red blood cell count),2017-03-12,b-usa-6579,2017-03-20,p-usa-0101,r-usa-i-1699,319.53,2556.24
4,cc-usa-1,adm-usa-0075,Autism spectrum disorder ASD,2019-03-08,b-usa-4693,2019-03-16,p-usa-0182,r-usa-iii-3491,77.11,616.88
...,...,...,...,...,...,...,...,...,...,...
950,cc-usa-2,adm-usa-9866,Atrioventricular node conduction block heart b...,2019-04-14,b-usa-9370,2019-05-04,p-usa-0190,r-usa-vip-7069,672.34,13446.80
951,cc-usa-2,adm-usa-9924,Encephalitis brain infection,2017-08-23,b-usa-0953,2017-08-25,p-usa-0991,r-usa-vvip-4521,919.31,1838.62
952,cc-usa-2,adm-usa-9953,Keratosis pilaris common skin condition,2012-02-15,b-usa-7209,2012-03-13,p-usa-0164,r-usa-ii-9195,184.48,4980.96
953,cc-usa-2,adm-usa-9956,Hiatal hernia stomach pushes through diaphragm,2020-05-06,b-usa-7422,2020-05-23,p-usa-0696,r-usa-i-8133,479.38,8149.46
954,cc-usa-2,adm-usa-9990,Keratitis inflammation of cornea,2018-08-01,b-usa-7495,2018-08-21,p-usa-0005,r-usa-vip-4712,672.34,13446.80

In [18]:
with open('./usa_test/patient_admissions_by_carecenter.pkl', 'wb') as fh:
    dump(patient_admissions_by_carecenter, fh)

In [19]:
patient_admissions_by_room = usa_instance.patient_admissions_by_room()
patient_admissions_by_room

Accessing DC: usa

,room_id,admission_id,admitted_causes,admitted_date,bed_id,care_center_id,discharged_date,patient_id,room_rate_per_night,room_rate_total
0,r-usa-vvip-9758,adm-usa-0133,Overdose,2017-09-05,b-usa-8576,cc-usa-2,2017-09-15,p-usa-0252,919.31,9193.10
1,r-usa-vvip-9758,adm-usa-0226,Radiation exposure radiation sickness,2022-01-02,b-usa-6824,cc-usa-2,2022-02-17,p-usa-0378,919.31,42288.26
2,r-usa-vvip-9758,adm-usa-0592,Ramsay Hunt syndrome viral infection causing f...,2013-01-12,b-usa-6011,cc-usa-2,2013-01-29,p-usa-0574,919.31,15628.27
3,r-usa-vvip-9758,adm-usa-4567,Estrogen withdrawal female hormone,2013-08-09,b-usa-8472,cc-usa-2,2013-08-14,p-usa-0057,919.31,4596.55
4,r-usa-vvip-9758,adm-usa-5288,Herpes simplex infection viral infection,2013-12-05,b-usa-6824,cc-usa-2,2013-12-27,p-usa-0495,919.31,20224.82
...,...,...,...,...,...,...,...,...,...,...
950,r-usa-vip-0055,adm-usa-7227,Fibroid uterine muscle tumor,2014-05-07,b-usa-4572,cc-usa-1,2014-05-31,p-usa-0729,520.66,12495.84
951,r-usa-vip-0055,adm-usa-7947,Congenital heart disease heart defect at birth,2019-06-12,b-usa-6124,cc-usa-1,2019-06-17,p-usa-0077,520.66,2603.30
952,r-usa-vip-0055,adm-usa-8350,Myocarditis heart muscle inflammation,2013-06-23,b-usa-7403,cc-usa-1,2013-07-28,p-usa-0687,520.66,18223.10
953,r-usa-vip-0055,adm-usa-8355,Hammer toes toe deformity,2014-02-22,b-usa-4592,cc-usa-2,2014-03-07,p-usa-0954,672.34,8740.42
954,r-usa-vip-0055,adm-usa-8742,Ovarian cyst female organ fluid collection,2018-11-28,b-usa-3389,cc-usa-2,2018-12-18,p-usa-0078,672.34,13446.80

In [20]:
with open('./usa_test/patient_admissions_by_room.pkl', 'wb') as fh:
    dump(patient_admissions_by_room, fh)

In [21]:
patient_admissions_by_city = usa_instance.patient_admissions_by_city()
patient_admissions_by_city

Accessing DC: usa

,city,admission_id,admitted_causes,admitted_date,bed_id,care_center_id,discharged_date,patient_id,room_id,room_rate_per_night,room_rate_total
0,B,adm-usa-0011,Common spider bite spider bite,2015-01-04,b-usa-1568,cc-usa-1,2015-01-13,p-usa-0956,r-usa-vip-2595,520.66,4685.94
1,B,adm-usa-0016,Compartment syndrome increased pressure inside...,2016-04-09,b-usa-5082,cc-usa-1,2016-05-03,p-usa-0564,r-usa-iii-2962,77.11,1850.64
2,B,adm-usa-0024,Hepatitis A,2013-08-29,b-usa-5041,cc-usa-1,2013-09-04,p-usa-0649,r-usa-iii-7582,77.11,462.66
3,B,adm-usa-0057,Anemia (low red blood cell count),2017-03-12,b-usa-6579,cc-usa-1,2017-03-20,p-usa-0101,r-usa-i-1699,319.53,2556.24
4,B,adm-usa-0075,Autism spectrum disorder ASD,2019-03-08,b-usa-4693,cc-usa-1,2019-03-16,p-usa-0182,r-usa-iii-3491,77.11,616.88
...,...,...,...,...,...,...,...,...,...,...,...
950,D,adm-usa-9866,Atrioventricular node conduction block heart b...,2019-04-14,b-usa-9370,cc-usa-2,2019-05-04,p-usa-0190,r-usa-vip-7069,672.34,13446.80
951,D,adm-usa-9924,Encephalitis brain infection,2017-08-23,b-usa-0953,cc-usa-2,2017-08-25,p-usa-0991,r-usa-vvip-4521,919.31,1838.62
952,D,adm-usa-9953,Keratosis pilaris common skin condition,2012-02-15,b-usa-7209,cc-usa-2,2012-03-13,p-usa-0164,r-usa-ii-9195,184.48,4980.96
953,D,adm-usa-9956,Hiatal hernia stomach pushes through diaphragm,2020-05-06,b-usa-7422,cc-usa-2,2020-05-23,p-usa-0696,r-usa-i-8133,479.38,8149.46
954,D,adm-usa-9990,Keratitis inflammation of cornea,2018-08-01,b-usa-7495,cc-usa-2,2018-08-21,p-usa-0005,r-usa-vip-4712,672.34,13446.80

In [22]:
with open('./usa_test/patient_admissions_by_city.pkl', 'wb') as fh:
    dump(patient_admissions_by_city, fh)

In [23]:
patient_admissions_by_state = usa_instance.patient_admissions_by_state()
patient_admissions_by_state

Accessing DC: usa

,state,admission_id,admitted_causes,admitted_date,bed_id,care_center_id,discharged_date,patient_id,room_id,room_rate_per_night,room_rate_total
0,T,adm-usa-0011,Common spider bite spider bite,2015-01-04,b-usa-1568,cc-usa-1,2015-01-13,p-usa-0956,r-usa-vip-2595,520.66,4685.94
1,T,adm-usa-0016,Compartment syndrome increased pressure inside...,2016-04-09,b-usa-5082,cc-usa-1,2016-05-03,p-usa-0564,r-usa-iii-2962,77.11,1850.64
2,T,adm-usa-0024,Hepatitis A,2013-08-29,b-usa-5041,cc-usa-1,2013-09-04,p-usa-0649,r-usa-iii-7582,77.11,462.66
3,T,adm-usa-0057,Anemia (low red blood cell count),2017-03-12,b-usa-6579,cc-usa-1,2017-03-20,p-usa-0101,r-usa-i-1699,319.53,2556.24
4,T,adm-usa-0075,Autism spectrum disorder ASD,2019-03-08,b-usa-4693,cc-usa-1,2019-03-16,p-usa-0182,r-usa-iii-3491,77.11,616.88
...,...,...,...,...,...,...,...,...,...,...,...
950,I,adm-usa-9866,Atrioventricular node conduction block heart b...,2019-04-14,b-usa-9370,cc-usa-2,2019-05-04,p-usa-0190,r-usa-vip-7069,672.34,13446.80
951,I,adm-usa-9924,Encephalitis brain infection,2017-08-23,b-usa-0953,cc-usa-2,2017-08-25,p-usa-0991,r-usa-vvip-4521,919.31,1838.62
952,I,adm-usa-9953,Keratosis pilaris common skin condition,2012-02-15,b-usa-7209,cc-usa-2,2012-03-13,p-usa-0164,r-usa-ii-9195,184.48,4980.96
953,I,adm-usa-9956,Hiatal hernia stomach pushes through diaphragm,2020-05-06,b-usa-7422,cc-usa-2,2020-05-23,p-usa-0696,r-usa-i-8133,479.38,8149.46
954,I,adm-usa-9990,Keratitis inflammation of cornea,2018-08-01,b-usa-7495,cc-usa-2,2018-08-21,p-usa-0005,r-usa-vip-4712,672.34,13446.80

In [24]:
with open('./usa_test/patient_admissions_by_state.pkl', 'wb') as fh:
    dump(patient_admissions_by_state, fh)

In [25]:
patient_admissions_by_country = usa_instance.patient_admissions_by_country()
patient_admissions_by_country

Accessing DC: usa

,country,admission_id,admitted_causes,admitted_date,bed_id,care_center_id,discharged_date,patient_id,room_id,room_rate_per_night,room_rate_total
0,USA,adm-usa-0011,Common spider bite spider bite,2015-01-04,b-usa-1568,cc-usa-1,2015-01-13,p-usa-0956,r-usa-vip-2595,520.66,4685.94
1,USA,adm-usa-0014,Tonsillar cancer tumor tongue,2016-09-15,b-usa-1987,cc-usa-2,2016-09-28,p-usa-0252,r-usa-vip-7400,672.34,8740.42
2,USA,adm-usa-0016,Compartment syndrome increased pressure inside...,2016-04-09,b-usa-5082,cc-usa-1,2016-05-03,p-usa-0564,r-usa-iii-2962,77.11,1850.64
3,USA,adm-usa-0024,Hepatitis A,2013-08-29,b-usa-5041,cc-usa-1,2013-09-04,p-usa-0649,r-usa-iii-7582,77.11,462.66
4,USA,adm-usa-0036,Thyroid cyst,2015-04-22,b-usa-0032,cc-usa-2,2015-05-02,p-usa-0707,r-usa-i-9320,479.38,4793.80
...,...,...,...,...,...,...,...,...,...,...,...
950,USA,adm-usa-9939,Bell's palsy facial muscle weakness,2014-06-24,b-usa-3734,cc-usa-1,2014-06-26,p-usa-0042,r-usa-vip-1650,520.66,1041.32
951,USA,adm-usa-9953,Keratosis pilaris common skin condition,2012-02-15,b-usa-7209,cc-usa-2,2012-03-13,p-usa-0164,r-usa-ii-9195,184.48,4980.96
952,USA,adm-usa-9956,Hiatal hernia stomach pushes through diaphragm,2020-05-06,b-usa-7422,cc-usa-2,2020-05-23,p-usa-0696,r-usa-i-8133,479.38,8149.46
953,USA,adm-usa-9973,Puncture wound of ankle,2018-12-14,b-usa-1154,cc-usa-1,2019-02-02,p-usa-0642,r-usa-iii-3491,77.11,3855.50
954,USA,adm-usa-9990,Keratitis inflammation of cornea,2018-08-01,b-usa-7495,cc-usa-2,2018-08-21,p-usa-0005,r-usa-vip-4712,672.34,13446.80

In [26]:
with open('./usa_test/patient_admissions_by_country.pkl', 'wb') as fh:
    dump(patient_admissions_by_country, fh)